arch: ppc64le
dist: bionic
sudo: required
services:
  - docker
compiler:
  - clang
  - gcc
script:
  - echo $TRAVIS_CPU_ARCH
  - docker pull ubuntu:18.04
  - docker run -dt --name test ubuntu:18.04
  - docker ps -a
  - sudo whoami
  - gcc --version
  - clang --version
